export const OPERATIONS_CATALOG = Object.freeze({
	en: {
		riskLow: "Low",
		riskMedium: "Medium",
		riskHigh: "High",
		riskCritical: "Critical",
		sourcePendingPurge: "Deletion pending",
		sourceUnusedExpired: "Unused source past retention",
		sourceOrphan: "Unregistered source",
		ready: "Ready to import",
		importing: "Importing",
		completed: "Completed",
		duplicateState: "Duplicate skipped",
		skippedState: "Skipped",
		workflow: "Import workflow",
		importProgress: "Processing & results",
		mappingHelp:
			"Match each CRM field to a column in your file. Required fields must be mapped before you can save a plan.",
		mappingIncomplete: "Map every required field to continue.",
		mappingReady:
			"Required fields are mapped. Review the sample, then validate your import plan.",
		sourceEmpty:
			"Start with a CSV or TSV file. You will review its columns and validate every row before importing.",
		reviewApprovals: "Review pending approvals",
		incidentQueue: "Review incidents",
		recordsShown: "Records shown",
		processedRows: "Processed rows",
		historyHelp:
			"Open a saved import to inspect its results or continue processing.",
		sourceFileError: "Choose a CSV or TSV file within the upload size limit.",
		sourceLoading: "Opening and checking source…",
		exportReport: "Download CSV report",
		exportReportHelp:
			"Exports all persisted row outcomes, not just this page. Cancelled or failed jobs may still have unprocessed rows. The file includes CRM record identifiers; share it carefully.",
		language: "Language for operation screens",
		migration: "Migration Center",
		intro:
			"Bring your contacts and companies across safely. Existing records are never overwritten.",
		upload: "1. Select a source",
		uploadHelp:
			"UTF-8 CSV or TSV, up to 512 KiB and 5,000 rows. XLSX is not enabled; export CSV from Excel.",
		selectFile: "Select file",
		storedSources: "Stored sources",
		preview: "Preview",
		remove: "Remove unused source",
		mapping: "2. Map columns",
		entity: "Import as",
		contact: "Contacts",
		company: "Companies",
		skip: "Do not import",
		required: "Required",
		prepare: "Validate and save plan",
		review: "3. Review before import",
		sourceRows: "Source rows",
		validRows: "Ready to process",
		invalidRows: "Validation rejected",
		run: "Start / resume import",
		stop: "Pause after current batch",
		cancel: "Cancel job",
		jobHelp:
			"Processing continues while this page stays open. Closing it stops new batches; return to resume from saved progress.",
		created: "Created",
		duplicates: "Duplicates skipped",
		rejected: "Rejected",
		remaining: "Not yet processed",
		rolledBack: "Archived by rollback",
		history: "Recent imports",
		report: "Open report",
		noJobs: "No imports yet. Start by uploading a source file.",
		notConfigured:
			"This deployment has not enabled Migration Center. Ask the administrator to configure the private source volume and encryption keys.",
		readOnly:
			"Preparation is available. CRM writes stay disabled until database acceptance is complete.",
		loading: "Loading…",
		error:
			"The operation could not be completed. Saved sources and committed rows are retained. Refresh the report before retrying.",
		refresh: "Refresh",
		row: "Source row",
		outcome: "Outcome",
		reason: "Reason",
		next: "Next page",
		first: "First page",
		reconciled: "Every source row has a recorded outcome; counters agree.",
		notReconciled:
			"Accounting is not complete yet. Review remaining rows and the job state.",
		confirmImport: "Start this saved import plan?",
		confirmHelp:
			"Only new contacts or companies are created. Exact matches are skipped, ambiguous matches are rejected. Phone normalization is Uzbekistan-specific. Records belong to the operator who prepared this job.",
		confirm: "Confirm",
		back: "Back",
		rollback: "Preview rollback",
		rollbackHelp:
			"Rollback archives only unchanged records created by this job and not linked to later work. It never deletes customer records or changes pre-existing duplicates.",
		applyRollback: "Archive eligible records on this page",
		deleteSource: "Remove this source permanently?",
		deleteHelp:
			"Deletion is allowed only when no saved job references the source. This cannot be undone.",
		noSource: "No source selected",
		planSaved: "Plan saved. No CRM records have been written.",
		status: "Status",
		firstName: "First name",
		lastName: "Last name",
		email: "Email",
		phone: "Uzbekistan phone",
		title: "Job title",
		name: "Company name",
		domain: "Domain (without https://)",
		partial:
			"This operation screen is localized; the rest of the workspace may still use English.",
		fileBusy: "Uploading and validating…",
		open: "Open",
		noRows: "No row outcomes on this page yet.",
		approve: "Approve",
		reject: "Reject",
		approvals: "Approvals",
		overview: "Operations",
		pending: "Pending",
		evidence: "Evidence",
		incident: "Incident",
		cost: "Recorded cost",
		unknown: "Not recorded",
		operations: "Agent Operations",
		operationsIntro:
			"Review recorded work, investigate failures, and decide on exact actions. Private agent drafts stay outside this view.",
		operationsError:
			"Data could not be refreshed. This is not evidence that everything is healthy. Refresh before making a decision.",
		adminOnly: "This view requires current workspace administrator access.",
		period: "Reporting window",
		lastDay: "Last 24 hours",
		lastWeek: "Last 7 days",
		activeAgents: "Active agents",
		runs: "Runs",
		actions: "Actions",
		agents: "Team agents",
		agent: "Agent",
		health: "Verification & coverage",
		noRuns:
			"No team-agent runs in this window. Start with one controlled task rather than demo data.",
		noActions: "No recorded actions in this window.",
		noIncidents:
			"No failed actions or matched ambiguous receipts in this window. This is not a provider health check.",
		noApprovals: "No approvals match this filter.",
		all: "All statuses",
		approved: "Approved",
		rejectedState: "Rejected",
		expired: "Expired",
		cancelled: "Cancelled",
		consumed: "Consumed once",
		requester: "Requested by",
		expires: "Expires",
		runId: "Run ID",
		openAgent: "Open agent",
		noOutcomeLedger:
			"Business outcomes and time saved are not instrumented yet. A successful run is not a verified financial result.",
		costHelp:
			"Sum of recorded run cost in USD. Missing costs are shown separately; provider charges and business ROI are not included.",
		missingCost: "Runs without recorded cost",
		successRate: "Success among completed / failed runs",
		providerUnknown:
			"Live connection health has not been verified by this screen.",
		coverageLimit:
			"This window exceeds the safe calculation limit. Full totals are not inferred from a partial sample; choose a shorter window.",
		recentLimit:
			"Lists show up to 50 recent rows. Open an agent for its full available history.",
		approvalDisabled:
			"Approval Center is disabled until its database acceptance gate is passed and the deployment administrator enables it.",
		approvalHelp:
			"Approval permits this exact action identity once. It does not restart a run or execute the action from this screen. Current permissions are checked again at execution.",
		legacyApproval:
			"Legacy request without a bound preview. It cannot be newly approved here.",
		incompletePreview:
			"The preview is redacted or truncated. Approval stays blocked until a complete safe preview is available.",
		decisionTitle: "Confirm this decision",
		decisionNote: "Optional note (do not paste secrets)",
		decisionSaved: "Decision saved. No run was restarted.",
		revokeApproval: "Cancel unused approval",
		ambiguous: "Reconciliation required — do not retry blindly",
		succeeded: "Succeeded",
		failed: "Failed",
		queued: "Queued",
		running: "Running",
		planned: "Planned",
		live: "Live",
		paused: "Paused",
		archived: "Archived",
		atTime: "Recorded at",
		actionType: "Action type",
		approvalRisk: "Manifest risk",
		lastSnapshot: "Database snapshot",
		receiptCoverage:
			"Some historical actions lack a governed receipt link. Incident totals are unknown; an empty list does not prove provider success.",
		continuations: "Continuations",
		continuationHelp:
			"Approval records a decision. The scheduler may resume only the original native tool call. Delivery is not proof that the action succeeded.",
		continuationDisabled:
			"Native continuation is disabled until database and pinned-runtime acceptance pass. Decisions are saved without automatic resume.",
		continuationEmpty: "No continuations match this filter.",
		continuationActive: "In progress",
		continuationAttention: "Needs reconciliation",
		continuationPrepared: "Preparing native wait",
		continuationBound: "Native request bound",
		continuationReady: "Waiting for decision or delivery",
		continuationDispatching: "Delivering the decision",
		continuationDelivered: "Decision delivered",
		continuationCompleted: "Action confirmed by receipt",
		continuationSafety:
			"Do not retry the whole run or create a new action key. Inspect the native session and provider receipt. Unknown delivery is never automatically resent.",
		continuationWaitingAt: "Waiting since",
		continuationDeliveredAt: "Decision delivered at",
		sourceMaintenance: "Source storage",
		sourceMaintenanceHelp:
			"Review unused sources older than 30 days, unfinished deletions and unregistered files older than 7 days. Every source linked to any import job is retained. Metadata and row receipts are never removed.",
		cleanupPreview: "Review cleanup plan",
		cleanupApply: "Delete reviewed source files",
		cleanupConfirm:
			"Delete only the files in this reviewed plan? Encrypted originals will be removed irreversibly from this volume; audit records remain. Restore requires a backup.",
		cleanupEmpty: "No eligible sources were found in this scan.",
		cleanupPartial:
			"This scan is bounded. More files may remain; repeat after reviewing these results.",
		cleanupPending: "Deletion pending — retry",
		cleanupResults: "Cleanup results",
		cleanupProtected: "Protected by import history",
		backgroundTitle: "Processing mode",
		backgroundHelp:
			"Background mode requires a separately running worker and shared persistent storage. Scheduling a job does not prove that a worker is online. Progress is based only on saved results.",
		backgroundStart: "Run in background",
		backgroundPause: "Pause background processing",
		backgroundConfirm:
			"Allow the configured worker to process this exact saved plan after you close this page? Committed rows remain; a pause drains a batch already in flight.",
		backgroundQueued: "Scheduled for the background worker",
		backgroundLocal: "This page controls processing",
		backgroundError:
			"Background processing stopped for review. Inspect the saved report before resuming.",
		backgroundNext: "Next eligible worker poll",
		purged: "File removed",
		reviewRequired: "Needs review",
	},
	ru: {
		riskLow: "Низкий",
		riskMedium: "Средний",
		riskHigh: "Высокий",
		riskCritical: "Критический",
		sourcePendingPurge: "Ожидает удаления",
		sourceUnusedExpired: "Неиспользуемый источник старше срока хранения",
		sourceOrphan: "Незарегистрированный источник",
		ready: "Готов к импорту",
		importing: "Импортируется",
		completed: "Завершён",
		duplicateState: "Дубликат пропущен",
		skippedState: "Пропущено",
		workflow: "Этапы импорта",
		importProgress: "Обработка и результаты",
		mappingHelp:
			"Сопоставьте поля CRM со столбцами файла. Для сохранения плана нужно заполнить все обязательные поля.",
		mappingIncomplete: "Сопоставьте все обязательные поля, чтобы продолжить.",
		mappingReady:
			"Обязательные поля сопоставлены. Проверьте пример и сохраните план импорта.",
		sourceEmpty:
			"Начните с файла CSV или TSV. Перед импортом вы проверите столбцы и каждую строку.",
		reviewApprovals: "Проверить ожидающие согласования",
		incidentQueue: "Проверить инциденты",
		recordsShown: "Записей в этой выборке",
		processedRows: "Обработано строк",
		historyHelp:
			"Откройте сохранённый импорт, чтобы проверить результаты или продолжить обработку.",
		sourceFileError:
			"Выберите CSV или TSV в пределах допустимого размера загрузки.",
		sourceLoading: "Открываем и проверяем источник…",
		exportReport: "Скачать CSV-отчёт",
		exportReportHelp:
			"Выгружаются все сохранённые результаты строк, а не только эта страница. У отменённых или неудачных заданий могут остаться необработанные строки. Файл содержит идентификаторы записей CRM: передавайте его осторожно.",
		language: "Язык рабочих экранов",
		migration: "Перенос данных",
		intro:
			"Безопасно перенесите контакты и компании. Существующие записи не перезаписываются.",
		upload: "1. Выберите файл",
		uploadHelp:
			"CSV или TSV в UTF-8, до 512 КиБ и 5 000 строк. XLSX пока не поддерживается: сохраните файл Excel как CSV.",
		selectFile: "Выбрать файл",
		storedSources: "Сохранённые файлы",
		preview: "Предпросмотр",
		remove: "Удалить неиспользуемый файл",
		mapping: "2. Сопоставьте столбцы",
		entity: "Что переносим",
		contact: "Контакты",
		company: "Компании",
		skip: "Не переносить",
		required: "Обязательно",
		prepare: "Проверить и сохранить план",
		review: "3. Проверьте перед запуском",
		sourceRows: "Строк в файле",
		validRows: "Готово к обработке",
		invalidRows: "Не прошли проверку",
		run: "Запустить / продолжить",
		stop: "Пауза после текущего пакета",
		cancel: "Отменить импорт",
		jobHelp:
			"Обработка идёт, пока открыта эта страница. После закрытия новые пакеты не запускаются; вернитесь, чтобы продолжить с сохранённого места.",
		created: "Создано",
		duplicates: "Дубли пропущены",
		rejected: "Отклонено",
		remaining: "Ещё не обработано",
		rolledBack: "Архивировано откатом",
		history: "Последние импорты",
		report: "Открыть отчёт",
		noJobs: "Импортов пока нет. Начните с загрузки файла.",
		notConfigured:
			"Перенос данных ещё не включён в этом развёртывании. Администратору нужно настроить постоянное закрытое хранилище и ключи шифрования.",
		readOnly:
			"Подготовка доступна. Запись в CRM отключена до проверки базы данных.",
		loading: "Загрузка…",
		error:
			"Не удалось завершить операцию. Файлы и подтверждённые записи сохранены. Обновите отчёт перед повторной попыткой.",
		refresh: "Обновить",
		row: "Строка файла",
		outcome: "Результат",
		reason: "Причина",
		next: "Следующая страница",
		first: "Первая страница",
		reconciled: "Для каждой строки записан результат, счётчики совпадают.",
		notReconciled:
			"Учёт строк ещё не завершён. Проверьте остаток и состояние импорта.",
		confirmImport: "Запустить сохранённый план импорта?",
		confirmHelp:
			"Создаются только новые контакты или компании. Точные совпадения пропускаются, неоднозначные отклоняются. Номера телефонов нормализуются для Узбекистана. Ответственным станет сотрудник, подготовивший план.",
		confirm: "Подтвердить",
		back: "Назад",
		rollback: "Предпросмотр отката",
		rollbackHelp:
			"Откат архивирует только неизменённые записи этого импорта без последующих связей. Записи не удаляются; существовавшие ранее дубли не затрагиваются.",
		applyRollback: "Архивировать доступные записи этой страницы",
		deleteSource: "Удалить исходный файл навсегда?",
		deleteHelp:
			"Удаление возможно, только если ни один сохранённый импорт не ссылается на файл. Восстановить его после удаления нельзя.",
		noSource: "Файл не выбран",
		planSaved: "План сохранён. Записей в CRM ещё не создано.",
		status: "Статус",
		firstName: "Имя",
		lastName: "Фамилия",
		email: "Электронная почта",
		phone: "Телефон Узбекистана",
		title: "Должность",
		name: "Название компании",
		domain: "Домен (без https://)",
		partial:
			"Этот рабочий экран переведён; другие разделы пока могут быть на английском.",
		fileBusy: "Загрузка и проверка…",
		open: "Открыть",
		noRows: "На этой странице пока нет результатов обработки строк.",
		approve: "Подтвердить",
		reject: "Отклонить",
		approvals: "Согласования",
		overview: "Операции",
		pending: "Ожидают решения",
		evidence: "Основания",
		incident: "Инцидент",
		cost: "Учтённая стоимость",
		unknown: "Не зафиксировано",
		operations: "Управление агентами",
		operationsIntro:
			"Проверяйте выполненную работу, разбирайте ошибки и согласовывайте конкретные действия. Личные черновики агентов здесь не показываются.",
		operationsError:
			"Не удалось обновить данные. Это не означает, что ошибок нет. Обновите экран перед принятием решения.",
		adminOnly:
			"Этот раздел доступен действующему администратору рабочего пространства.",
		period: "Период",
		lastDay: "Последние 24 часа",
		lastWeek: "Последние 7 дней",
		activeAgents: "Активные агенты",
		runs: "Запуски",
		actions: "Действия",
		agents: "Агенты команды",
		agent: "Агент",
		health: "Проверка и полнота данных",
		noRuns:
			"За этот период запусков нет. Начните с одной контролируемой задачи, а не с демонстрационных данных.",
		noActions: "За этот период нет записанных действий.",
		noIncidents:
			"В этом периоде не найдено ошибочных действий или связанных квитанций с неопределённым результатом. Это не проверка внешних сервисов.",
		noApprovals: "Согласований с таким статусом нет.",
		all: "Все статусы",
		approved: "Согласовано",
		rejectedState: "Отклонено",
		expired: "Срок истёк",
		cancelled: "Отменено",
		consumed: "Использовано",
		requester: "Инициатор",
		expires: "Действует до",
		runId: "ID запуска",
		openAgent: "Открыть агента",
		noOutcomeLedger:
			"Бизнес-результаты и экономия времени пока не измеряются. Успешный запуск не равен подтверждённому финансовому результату.",
		costHelp:
			"Сумма записанной стоимости запусков в USD. Пропуски учитываются отдельно; расходы провайдеров и ROI не входят в эту цифру.",
		missingCost: "Запуски без записанной стоимости",
		successRate: "Успех среди завершённых и ошибочных запусков",
		providerUnknown:
			"Этот экран не подтверждает работоспособность внешних подключений.",
		coverageLimit:
			"Период превышает безопасный лимит расчёта. Итоги не вычисляются по неполной выборке; выберите более короткий период.",
		recentLimit:
			"В списках — до 50 последних записей. Доступная история находится в карточке агента.",
		approvalDisabled:
			"Центр согласований отключён до проверки схемы и транзакций БД и включения администратором развёртывания.",
		approvalHelp:
			"Согласование разрешает одно выполнение именно этого действия. Экран не перезапускает агента и не выполняет действие. Права повторно проверяются перед выполнением.",
		legacyApproval:
			"Старая заявка без привязанного снимка действия. Согласовать её здесь нельзя.",
		incompletePreview:
			"Данные скрыты или сокращены. Согласование заблокировано до появления полного безопасного предварительного просмотра.",
		decisionTitle: "Подтвердите решение",
		decisionNote: "Комментарий, необязательно (без секретов)",
		decisionSaved: "Решение сохранено. Запуск не перезапускался.",
		revokeApproval: "Отменить неиспользованное согласование",
		ambiguous: "Нужна сверка — не повторяйте вслепую",
		succeeded: "Успешно",
		failed: "Ошибка",
		queued: "В очереди",
		running: "Выполняется",
		planned: "Запланировано",
		live: "Работает",
		paused: "Приостановлен",
		archived: "В архиве",
		atTime: "Зафиксировано",
		actionType: "Тип действия",
		approvalRisk: "Риск по описанию действия",
		lastSnapshot: "Снимок базы данных",
		receiptCoverage:
			"Для части прошлых действий нет связи с governed-квитанцией. Полный счётчик инцидентов неизвестен: пустой список не подтверждает успех у провайдера.",
		continuations: "Продолжения",
		continuationHelp:
			"Согласование сохраняет решение. Планировщик может продолжить только исходный вызов инструмента. Доставка решения ещё не означает успех действия.",
		continuationDisabled:
			"Автопродолжение выключено до проверки БД и закреплённой версии runtime. Решения сохраняются без автоматического возобновления.",
		continuationEmpty: "Продолжений с таким состоянием нет.",
		continuationActive: "В работе",
		continuationAttention: "Нужна сверка",
		continuationPrepared: "Подготовка ожидания",
		continuationBound: "Запрос инструмента привязан",
		continuationReady: "Ожидает решения или доставки",
		continuationDispatching: "Передача решения",
		continuationDelivered: "Решение доставлено",
		continuationCompleted: "Действие подтверждено квитанцией",
		continuationSafety:
			"Не повторяйте весь запуск и не создавайте новый ключ действия. Проверьте исходную сессию и квитанцию провайдера. Неопределённая доставка автоматически не повторяется.",
		continuationWaitingAt: "Ожидает с",
		continuationDeliveredAt: "Решение доставлено",
		sourceMaintenance: "Хранилище источников",
		sourceMaintenanceHelp:
			"Проверьте неиспользуемые источники старше 30 дней, незавершённые удаления и незарегистрированные файлы старше 7 дней. Источники всех заданий сохраняются. Метаданные и квитанции строк не удаляются.",
		cleanupPreview: "Проверить план очистки",
		cleanupApply: "Удалить проверенные файлы",
		cleanupConfirm:
			"Удалить только файлы из этого плана? Зашифрованные оригиналы будут безвозвратно удалены с этого тома; журнал останется. Для восстановления потребуется резервная копия.",
		cleanupEmpty: "В этой выборке нет источников для очистки.",
		cleanupPartial:
			"Размер проверки ограничен. Могут остаться другие файлы; после просмотра результатов повторите проверку.",
		cleanupPending: "Удаление не завершено — повторить",
		cleanupResults: "Результаты очистки",
		cleanupProtected: "Защищены историей импорта",
		backgroundTitle: "Режим обработки",
		backgroundHelp:
			"Для фоновой обработки нужен отдельно запущенный worker с постоянным хранилищем. Постановка задания не доказывает, что worker работает. Прогресс отражает только сохранённые результаты.",
		backgroundStart: "Обрабатывать в фоне",
		backgroundPause: "Приостановить фоновую обработку",
		backgroundConfirm:
			"Разрешить настроенному worker обработать именно этот сохранённый план после закрытия страницы? Сохранённые строки останутся; уже начатый пакет может завершиться после паузы.",
		backgroundQueued: "Ожидает фонового worker",
		backgroundLocal: "Обработкой управляет эта страница",
		backgroundError:
			"Фоновая обработка остановлена для проверки. Перед продолжением изучите сохранённый отчёт.",
		backgroundNext: "Следующий допустимый опрос",
		purged: "Файл удалён",
		reviewRequired: "Нужна проверка",
	},
	uz: {
		riskLow: "Past",
		riskMedium: "O‘rtacha",
		riskHigh: "Yuqori",
		riskCritical: "Juda yuqori",
		sourcePendingPurge: "O‘chirish kutilmoqda",
		sourceUnusedExpired: "Saqlash muddati o‘tgan ishlatilmagan manba",
		sourceOrphan: "Ro‘yxatdan o‘tmagan manba",
		ready: "Importga tayyor",
		importing: "Import qilinmoqda",
		completed: "Tugallangan",
		duplicateState: "Dublikat o‘tkazib yuborildi",
		skippedState: "O‘tkazib yuborildi",
		workflow: "Import bosqichlari",
		importProgress: "Qayta ishlash va natijalar",
		mappingHelp:
			"CRM maydonlarini fayl ustunlariga moslang. Rejani saqlash uchun barcha majburiy maydonlar moslangan bo‘lishi kerak.",
		mappingIncomplete: "Davom etish uchun barcha majburiy maydonlarni moslang.",
		mappingReady:
			"Majburiy maydonlar moslandi. Namunani tekshiring va import rejasini saqlang.",
		sourceEmpty:
			"CSV yoki TSV faylidan boshlang. Importdan oldin ustunlar va har bir qator tekshiriladi.",
		reviewApprovals: "Kutilayotgan tasdiqlashlarni ko‘rish",
		incidentQueue: "Hodisalarni tekshirish",
		recordsShown: "Ko‘rsatilgan yozuvlar",
		processedRows: "Ishlangan qatorlar",
		historyHelp:
			"Natijalarni tekshirish yoki qayta ishlashni davom ettirish uchun saqlangan importni oching.",
		sourceFileError: "Yuklash chegarasi ichidagi CSV yoki TSV faylini tanlang.",
		sourceLoading: "Manba ochilmoqda va tekshirilmoqda…",
		exportReport: "CSV hisobotni yuklab olish",
		exportReportHelp:
			"Faqat shu sahifa emas, barcha saqlangan satr natijalari yuklanadi. Bekor qilingan yoki xato bilan tugagan vazifalarda ishlanmagan satrlar qolishi mumkin. Faylda CRM yozuvlari identifikatorlari bor: uni ehtiyotkorlik bilan ulashing.",
		language: "Ish ekranlari tili",
		migration: "Ma’lumotlarni ko‘chirish",
		intro:
			"Kontaktlar va kompaniyalarni xavfsiz ko‘chiring. Mavjud yozuvlar ustidan yozilmaydi.",
		upload: "1. Faylni tanlang",
		uploadHelp:
			"UTF-8 formatidagi CSV yoki TSV, 512 KiB va 5 000 qatorgacha. XLSX hali qo‘llanmaydi: Excel faylini CSV sifatida saqlang.",
		selectFile: "Fayl tanlash",
		storedSources: "Saqlangan fayllar",
		preview: "Oldindan ko‘rish",
		remove: "Ishlatilmagan faylni o‘chirish",
		mapping: "2. Ustunlarni moslang",
		entity: "Nimani ko‘chiramiz",
		contact: "Kontaktlar",
		company: "Kompaniyalar",
		skip: "Ko‘chirilmasin",
		required: "Majburiy",
		prepare: "Tekshirish va rejani saqlash",
		review: "3. Boshlashdan oldin tekshiring",
		sourceRows: "Fayldagi qatorlar",
		validRows: "Ishlashga tayyor",
		invalidRows: "Tekshiruvdan o‘tmadi",
		run: "Boshlash / davom etish",
		stop: "Joriy paketdan keyin to‘xtatish",
		cancel: "Importni bekor qilish",
		jobHelp:
			"Sahifa ochiq turganda ishlov beriladi. Uni yopsangiz, yangi paketlar boshlanmaydi; davom etish uchun qayting.",
		created: "Yaratildi",
		duplicates: "Dublikatlar o‘tkazib yuborildi",
		rejected: "Rad etildi",
		remaining: "Hali ishlanmagan",
		rolledBack: "Qaytarishda arxivlandi",
		history: "So‘nggi importlar",
		report: "Hisobotni ochish",
		noJobs: "Hali import yo‘q. Avval fayl yuklang.",
		notConfigured:
			"Bu o‘rnatishda import hali yoqilmagan. Administrator yopiq doimiy saqlash joyi va shifrlash kalitlarini sozlashi kerak.",
		readOnly:
			"Tayyorlash mumkin. Baza tekshirilmaguncha CRM ga yozish o‘chirilgan.",
		loading: "Yuklanmoqda…",
		error:
			"Amal tugamadi. Fayllar va tasdiqlangan yozuvlar saqlangan. Qayta urinishdan oldin hisobotni yangilang.",
		refresh: "Yangilash",
		row: "Fayl qatori",
		outcome: "Natija",
		reason: "Sabab",
		next: "Keyingi sahifa",
		first: "Birinchi sahifa",
		reconciled: "Har bir qator natijasi yozilgan, hisoblagichlar mos.",
		notReconciled:
			"Qatorlar hisobi hali tugamagan. Qoldiq va import holatini tekshiring.",
		confirmImport: "Saqlangan import rejasini boshlaysizmi?",
		confirmHelp:
			"Faqat yangi kontakt yoki kompaniyalar yaratiladi. Aniq mosliklar o‘tkaziladi, noaniqlari rad etiladi. Telefonlar O‘zbekiston formatiga keltiriladi. Mas’ul — rejani tayyorlagan xodim.",
		confirm: "Tasdiqlash",
		back: "Orqaga",
		rollback: "Qaytarishni oldindan ko‘rish",
		rollbackHelp:
			"Faqat shu import yaratgan, keyinchalik o‘zgarmagan va bog‘lanmagan yozuvlar arxivlanadi. Yozuvlar o‘chirilmaydi, avvalgi dublikatlarga tegilmaydi.",
		applyRollback: "Bu sahifadagi mos yozuvlarni arxivlash",
		deleteSource: "Manba faylini butunlay o‘chirasizmi?",
		deleteHelp:
			"Faylga hech bir saqlangan import bog‘lanmagan bo‘lsa, uni o‘chirish mumkin. Uni qayta tiklab bo‘lmaydi.",
		noSource: "Fayl tanlanmagan",
		planSaved: "Reja saqlandi. CRM ga hali hech narsa yozilmadi.",
		status: "Holat",
		firstName: "Ism",
		lastName: "Familiya",
		email: "Elektron pochta",
		phone: "O‘zbekiston telefoni",
		title: "Lavozim",
		name: "Kompaniya nomi",
		domain: "Domen (https:// siz)",
		partial:
			"Bu ish ekrani tarjima qilingan; boshqa bo‘limlar hali inglizcha bo‘lishi mumkin.",
		fileBusy: "Yuklash va tekshirish…",
		open: "Ochish",
		noRows: "Bu sahifada hali qator natijalari yo‘q.",
		approve: "Tasdiqlash",
		reject: "Rad etish",
		approvals: "Tasdiqlashlar",
		overview: "Amallar",
		pending: "Qaror kutilmoqda",
		evidence: "Asoslar",
		incident: "Hodisa",
		cost: "Qayd etilgan xarajat",
		unknown: "Qayd etilmagan",
		operations: "Agentlar boshqaruvi",
		operationsIntro:
			"Bajarilgan ishlarni tekshiring, xatolarni ko‘rib chiqing va aniq amallarni tasdiqlang. Shaxsiy agent qoralamalari bu yerda ko‘rsatilmaydi.",
		operationsError:
			"Ma’lumotlarni yangilab bo‘lmadi. Bu xatolar yo‘qligini anglatmaydi. Qaror qabul qilishdan oldin yangilang.",
		adminOnly:
			"Bu bo‘lim uchun ish maydonining amaldagi administrator huquqi kerak.",
		period: "Davr",
		lastDay: "Oxirgi 24 soat",
		lastWeek: "Oxirgi 7 kun",
		activeAgents: "Faol agentlar",
		runs: "Ishga tushirishlar",
		actions: "Amallar",
		agents: "Jamoa agentlari",
		agent: "Agent",
		health: "Tekshiruv va qamrov",
		noRuns:
			"Bu davrda jamoa agentlari ishga tushirilmagan. Namuna ma’lumotlaridan emas, bitta nazoratli vazifadan boshlang.",
		noActions: "Bu davrda qayd etilgan amallar yo‘q.",
		noIncidents:
			"Bu davrda xatoli amallar yoki bog‘langan noaniq natija kvitansiyalari topilmadi. Bu tashqi xizmatlar holati tekshiruvi emas.",
		noApprovals: "Ushbu holatga mos tasdiqlashlar yo‘q.",
		all: "Barcha holatlar",
		approved: "Tasdiqlangan",
		rejectedState: "Rad etilgan",
		expired: "Muddati tugagan",
		cancelled: "Bekor qilingan",
		consumed: "Bir marta ishlatilgan",
		requester: "So‘rovchi",
		expires: "Amal qilish muddati",
		runId: "Ishga tushirish ID",
		openAgent: "Agentni ochish",
		noOutcomeLedger:
			"Biznes natijalari va tejalgan vaqt hali o‘lchanmaydi. Muvaffaqiyatli ishga tushirish tasdiqlangan moliyaviy natija emas.",
		costHelp:
			"USDda qayd etilgan ishga tushirish xarajatlari yig‘indisi. Yetishmagan xarajatlar alohida ko‘rsatiladi; provayder to‘lovlari va ROI bu raqamga kirmaydi.",
		missingCost: "Xarajati qayd etilmagan ishga tushirishlar",
		successRate:
			"Yakunlangan va xatoli ishga tushirishlar orasidagi muvaffaqiyat",
		providerUnknown: "Bu ekran tashqi ulanishlarning ishlashini tasdiqlamaydi.",
		coverageLimit:
			"Davr xavfsiz hisoblash chegarasidan oshdi. To‘liq natijalar qisman namunadan hisoblanmaydi; qisqaroq davrni tanlang.",
		recentLimit:
			"Ro‘yxatlarda oxirgi 50 tagacha yozuv ko‘rsatiladi. Mavjud tarixni agent sahifasida ko‘ring.",
		approvalDisabled:
			"Tasdiqlash markazi ma’lumotlar bazasi tekshiruvidan o‘tib, administrator yoqmaguncha o‘chirilgan.",
		approvalHelp:
			"Tasdiqlash aynan shu amalni bir marta bajarishga ruxsat beradi. Bu ekran agentni qayta ishga tushirmaydi yoki amalni bajarmaydi. Bajarishdan oldin huquqlar qayta tekshiriladi.",
		legacyApproval:
			"Amalga bog‘langan ko‘rinishsiz eski so‘rov. Uni bu yerda tasdiqlab bo‘lmaydi.",
		incompletePreview:
			"Ko‘rinishdagi ma’lumotlar yashirilgan yoki qisqartirilgan. To‘liq xavfsiz ko‘rinish bo‘lmaguncha tasdiqlash bloklanadi.",
		decisionTitle: "Qarorni tasdiqlang",
		decisionNote: "Izoh, ixtiyoriy (maxfiy ma’lumotlarsiz)",
		decisionSaved: "Qaror saqlandi. Agent qayta ishga tushirilmadi.",
		revokeApproval: "Ishlatilmagan tasdiqlashni bekor qilish",
		ambiguous: "Solishtirish kerak — tekshirmasdan qayta urinmang",
		succeeded: "Muvaffaqiyatli",
		failed: "Xato",
		queued: "Navbatda",
		running: "Bajarilmoqda",
		planned: "Rejalashtirilgan",
		live: "Faol",
		paused: "To‘xtatilgan",
		archived: "Arxivlangan",
		atTime: "Qayd etilgan vaqt",
		actionType: "Amal turi",
		approvalRisk: "Amal tavsifidagi xavf",
		lastSnapshot: "Ma’lumotlar bazasi holati",
		receiptCoverage:
			"Ayrim oldingi amallarda boshqariladigan kvitansiya bilan bog‘lanish yo‘q. Hodisalarning to‘liq soni noma’lum; bo‘sh ro‘yxat provayderdagi muvaffaqiyatni tasdiqlamaydi.",
		continuations: "Davom ettirish",
		continuationHelp:
			"Tasdiqlash qarorni saqlaydi. Rejalashtiruvchi faqat dastlabki vosita chaqiruvini davom ettirishi mumkin. Qaror yetkazilishi amal muvaffaqiyatini bildirmaydi.",
		continuationDisabled:
			"Ma’lumotlar bazasi va belgilangan runtime versiyasi tekshirilmaguncha avtomatik davom ettirish o‘chiq. Qarorlar saqlanadi, ish avtomatik boshlanmaydi.",
		continuationEmpty: "Ushbu holatda davom ettiriladigan ishlar yo‘q.",
		continuationActive: "Jarayonda",
		continuationAttention: "Natijani tekshirish kerak",
		continuationPrepared: "Kutishga tayyorlanmoqda",
		continuationBound: "Vosita so‘rovi bog‘langan",
		continuationReady: "Qaror yoki yetkazishni kutmoqda",
		continuationDispatching: "Qaror yuborilmoqda",
		continuationDelivered: "Qaror yetkazildi",
		continuationCompleted: "Amal kvitansiya bilan tasdiqlangan",
		continuationSafety:
			"Butun ishga tushirishni takrorlamang va yangi amal kalitini yaratmang. Dastlabki sessiya va provayder kvitansiyasini tekshiring. Noaniq yetkazish avtomatik takrorlanmaydi.",
		continuationWaitingAt: "Kutish boshlangan vaqt",
		continuationDeliveredAt: "Qaror yetkazilgan vaqt",
		sourceMaintenance: "Manbalar ombori",
		sourceMaintenanceHelp:
			"30 kundan eski foydalanilmagan manbalar, tugallanmagan o‘chirishlar va 7 kundan eski ro‘yxatdan o‘tmagan fayllarni tekshiring. Import vazifalariga bog‘langan manbalar saqlanadi. Metama’lumotlar va qator kvitansiyalari o‘chirilmaydi.",
		cleanupPreview: "Tozalash rejasini tekshirish",
		cleanupApply: "Tekshirilgan fayllarni o‘chirish",
		cleanupConfirm:
			"Faqat ushbu rejadagi fayllar o‘chirilsinmi? Shifrlangan asl fayllar bu diskdan butunlay o‘chiriladi; jurnal saqlanadi. Tiklash uchun zaxira nusxa kerak.",
		cleanupEmpty: "Bu tekshiruvda tozalash uchun manba topilmadi.",
		cleanupPartial:
			"Tekshiruv hajmi cheklangan. Boshqa fayllar qolgan bo‘lishi mumkin; natijalarni ko‘rib, tekshiruvni takrorlang.",
		cleanupPending: "O‘chirish tugamadi — qayta urinish",
		cleanupResults: "Tozalash natijalari",
		cleanupProtected: "Import tarixi bilan himoyalangan",
		backgroundTitle: "Qayta ishlash rejimi",
		backgroundHelp:
			"Fon rejimi uchun alohida ishlayotgan worker va doimiy ombor kerak. Navbatga qo‘yish worker ishlayotganini tasdiqlamaydi. Jarayon faqat saqlangan natijalarni ko‘rsatadi.",
		backgroundStart: "Fonda qayta ishlash",
		backgroundPause: "Fon jarayonini to‘xtatib turish",
		backgroundConfirm:
			"Sozlangan worker sahifa yopilgandan keyin aynan shu saqlangan rejani bajarsinmi? Saqlangan qatorlar qoladi; boshlangan paket pauzadan keyin tugashi mumkin.",
		backgroundQueued: "Fon worker navbatida",
		backgroundLocal: "Jarayonni ushbu sahifa boshqaradi",
		backgroundError:
			"Fon jarayoni tekshiruv uchun to‘xtatildi. Davom etishdan oldin saqlangan hisobotni ko‘ring.",
		backgroundNext: "Keyingi ruxsat etilgan tekshiruv",
		purged: "Fayl o‘chirildi",
		reviewRequired: "Tekshiruv kerak",
	},
});
export function operationsLocale(value) {
	return ["en", "ru", "uz"].includes(value) ? value : "en";
}
